// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ucesb.proto

#include "ucesb.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_ucesb_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LogEntry_ucesb_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_ucesb_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_UcesbSummary_ucesb_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_ucesb_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UcesbSummary_Triggers_ucesb_2eproto;
namespace frs_monitor {
class UcesbSummary_TriggersDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UcesbSummary_Triggers> _instance;
} _UcesbSummary_Triggers_default_instance_;
class UcesbSummaryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UcesbSummary> _instance;
} _UcesbSummary_default_instance_;
class LogEntryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LogEntry> _instance;
} _LogEntry_default_instance_;
class UcesbReportDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UcesbReport> _instance;
} _UcesbReport_default_instance_;
}  // namespace frs_monitor
static void InitDefaultsscc_info_LogEntry_ucesb_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::frs_monitor::_LogEntry_default_instance_;
    new (ptr) ::frs_monitor::LogEntry();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::frs_monitor::LogEntry::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LogEntry_ucesb_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_LogEntry_ucesb_2eproto}, {}};

static void InitDefaultsscc_info_UcesbReport_ucesb_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::frs_monitor::_UcesbReport_default_instance_;
    new (ptr) ::frs_monitor::UcesbReport();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::frs_monitor::UcesbReport::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_UcesbReport_ucesb_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_UcesbReport_ucesb_2eproto}, {
      &scc_info_UcesbSummary_ucesb_2eproto.base,
      &scc_info_LogEntry_ucesb_2eproto.base,}};

static void InitDefaultsscc_info_UcesbSummary_ucesb_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::frs_monitor::_UcesbSummary_default_instance_;
    new (ptr) ::frs_monitor::UcesbSummary();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::frs_monitor::UcesbSummary::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_UcesbSummary_ucesb_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_UcesbSummary_ucesb_2eproto}, {
      &scc_info_UcesbSummary_Triggers_ucesb_2eproto.base,}};

static void InitDefaultsscc_info_UcesbSummary_Triggers_ucesb_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::frs_monitor::_UcesbSummary_Triggers_default_instance_;
    new (ptr) ::frs_monitor::UcesbSummary_Triggers();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::frs_monitor::UcesbSummary_Triggers::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UcesbSummary_Triggers_ucesb_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_UcesbSummary_Triggers_ucesb_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ucesb_2eproto[4];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_ucesb_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ucesb_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ucesb_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary_Triggers, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary_Triggers, name_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary_Triggers, rate_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, server_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, clients_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, event_no_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, time_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, wr_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, triggers_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, onspill_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, lastspill_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, spilltime_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, extrtime_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, spill_ctr_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbSummary, analserver_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frs_monitor::LogEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frs_monitor::LogEntry, severity_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::LogEntry, message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbReport, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbReport, summary_),
  PROTOBUF_FIELD_OFFSET(::frs_monitor::UcesbReport, logs_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::frs_monitor::UcesbSummary_Triggers)},
  { 7, -1, sizeof(::frs_monitor::UcesbSummary)},
  { 24, -1, sizeof(::frs_monitor::LogEntry)},
  { 31, -1, sizeof(::frs_monitor::UcesbReport)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frs_monitor::_UcesbSummary_Triggers_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frs_monitor::_UcesbSummary_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frs_monitor::_LogEntry_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frs_monitor::_UcesbReport_default_instance_),
};

const char descriptor_table_protodef_ucesb_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013ucesb.proto\022\013frs_monitor\"\251\002\n\014UcesbSumm"
  "ary\022\016\n\006server\030\001 \001(\t\022\017\n\007clients\030\002 \001(\005\022\020\n\010"
  "event_no\030\003 \001(\004\022\014\n\004time\030\004 \001(\005\022\n\n\002wr\030\005 \001(\004"
  "\0224\n\010triggers\030\006 \003(\0132\".frs_monitor.UcesbSu"
  "mmary.Triggers\022\017\n\007onspill\030\007 \001(\010\022\021\n\tlasts"
  "pill\030\010 \001(\005\022\021\n\tspilltime\030\t \001(\005\022\020\n\010extrtim"
  "e\030\n \001(\005\022\021\n\tspill_ctr\030\013 \001(\r\022\022\n\nanalserver"
  "\030\014 \001(\t\032&\n\010Triggers\022\014\n\004name\030\001 \001(\t\022\014\n\004rate"
  "\030\002 \001(\005\"\203\001\n\010LogEntry\0223\n\010severity\030\001 \001(\0162!."
  "frs_monitor.LogEntry.LogSeverity\022\017\n\007mess"
  "age\030\002 \001(\t\"1\n\013LogSeverity\022\n\n\006NORMAL\020\000\022\013\n\007"
  "WARNING\020\001\022\t\n\005ERROR\020\002\"^\n\013UcesbReport\022*\n\007s"
  "ummary\030\001 \001(\0132\031.frs_monitor.UcesbSummary\022"
  "#\n\004logs\030\004 \003(\0132\025.frs_monitor.LogEntryb\006pr"
  "oto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ucesb_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_ucesb_2eproto_sccs[4] = {
  &scc_info_LogEntry_ucesb_2eproto.base,
  &scc_info_UcesbReport_ucesb_2eproto.base,
  &scc_info_UcesbSummary_ucesb_2eproto.base,
  &scc_info_UcesbSummary_Triggers_ucesb_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ucesb_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ucesb_2eproto = {
  false, false, descriptor_table_protodef_ucesb_2eproto, "ucesb.proto", 564,
  &descriptor_table_ucesb_2eproto_once, descriptor_table_ucesb_2eproto_sccs, descriptor_table_ucesb_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_ucesb_2eproto::offsets,
  file_level_metadata_ucesb_2eproto, 4, file_level_enum_descriptors_ucesb_2eproto, file_level_service_descriptors_ucesb_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ucesb_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_ucesb_2eproto)), true);
namespace frs_monitor {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogEntry_LogSeverity_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ucesb_2eproto);
  return file_level_enum_descriptors_ucesb_2eproto[0];
}
bool LogEntry_LogSeverity_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr LogEntry_LogSeverity LogEntry::NORMAL;
constexpr LogEntry_LogSeverity LogEntry::WARNING;
constexpr LogEntry_LogSeverity LogEntry::ERROR;
constexpr LogEntry_LogSeverity LogEntry::LogSeverity_MIN;
constexpr LogEntry_LogSeverity LogEntry::LogSeverity_MAX;
constexpr int LogEntry::LogSeverity_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void UcesbSummary_Triggers::InitAsDefaultInstance() {
}
class UcesbSummary_Triggers::_Internal {
 public:
};

UcesbSummary_Triggers::UcesbSummary_Triggers(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:frs_monitor.UcesbSummary.Triggers)
}
UcesbSummary_Triggers::UcesbSummary_Triggers(const UcesbSummary_Triggers& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  rate_ = from.rate_;
  // @@protoc_insertion_point(copy_constructor:frs_monitor.UcesbSummary.Triggers)
}

void UcesbSummary_Triggers::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UcesbSummary_Triggers_ucesb_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  rate_ = 0;
}

UcesbSummary_Triggers::~UcesbSummary_Triggers() {
  // @@protoc_insertion_point(destructor:frs_monitor.UcesbSummary.Triggers)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UcesbSummary_Triggers::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void UcesbSummary_Triggers::ArenaDtor(void* object) {
  UcesbSummary_Triggers* _this = reinterpret_cast< UcesbSummary_Triggers* >(object);
  (void)_this;
}
void UcesbSummary_Triggers::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UcesbSummary_Triggers::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UcesbSummary_Triggers& UcesbSummary_Triggers::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UcesbSummary_Triggers_ucesb_2eproto.base);
  return *internal_default_instance();
}


void UcesbSummary_Triggers::Clear() {
// @@protoc_insertion_point(message_clear_start:frs_monitor.UcesbSummary.Triggers)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  rate_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UcesbSummary_Triggers::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "frs_monitor.UcesbSummary.Triggers.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 rate = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          rate_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UcesbSummary_Triggers::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:frs_monitor.UcesbSummary.Triggers)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "frs_monitor.UcesbSummary.Triggers.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // int32 rate = 2;
  if (this->rate() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_rate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:frs_monitor.UcesbSummary.Triggers)
  return target;
}

size_t UcesbSummary_Triggers::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:frs_monitor.UcesbSummary.Triggers)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // int32 rate = 2;
  if (this->rate() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_rate());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UcesbSummary_Triggers::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:frs_monitor.UcesbSummary.Triggers)
  GOOGLE_DCHECK_NE(&from, this);
  const UcesbSummary_Triggers* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UcesbSummary_Triggers>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:frs_monitor.UcesbSummary.Triggers)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:frs_monitor.UcesbSummary.Triggers)
    MergeFrom(*source);
  }
}

void UcesbSummary_Triggers::MergeFrom(const UcesbSummary_Triggers& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:frs_monitor.UcesbSummary.Triggers)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.rate() != 0) {
    _internal_set_rate(from._internal_rate());
  }
}

void UcesbSummary_Triggers::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:frs_monitor.UcesbSummary.Triggers)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UcesbSummary_Triggers::CopyFrom(const UcesbSummary_Triggers& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:frs_monitor.UcesbSummary.Triggers)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UcesbSummary_Triggers::IsInitialized() const {
  return true;
}

void UcesbSummary_Triggers::InternalSwap(UcesbSummary_Triggers* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(rate_, other->rate_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UcesbSummary_Triggers::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void UcesbSummary::InitAsDefaultInstance() {
}
class UcesbSummary::_Internal {
 public:
};

UcesbSummary::UcesbSummary(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  triggers_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:frs_monitor.UcesbSummary)
}
UcesbSummary::UcesbSummary(const UcesbSummary& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      triggers_(from.triggers_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  server_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_server().empty()) {
    server_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_server(),
      GetArena());
  }
  analserver_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_analserver().empty()) {
    analserver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_analserver(),
      GetArena());
  }
  ::memcpy(&event_no_, &from.event_no_,
    static_cast<size_t>(reinterpret_cast<char*>(&spill_ctr_) -
    reinterpret_cast<char*>(&event_no_)) + sizeof(spill_ctr_));
  // @@protoc_insertion_point(copy_constructor:frs_monitor.UcesbSummary)
}

void UcesbSummary::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UcesbSummary_ucesb_2eproto.base);
  server_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  analserver_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&event_no_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&spill_ctr_) -
      reinterpret_cast<char*>(&event_no_)) + sizeof(spill_ctr_));
}

UcesbSummary::~UcesbSummary() {
  // @@protoc_insertion_point(destructor:frs_monitor.UcesbSummary)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UcesbSummary::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  server_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  analserver_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void UcesbSummary::ArenaDtor(void* object) {
  UcesbSummary* _this = reinterpret_cast< UcesbSummary* >(object);
  (void)_this;
}
void UcesbSummary::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UcesbSummary::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UcesbSummary& UcesbSummary::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UcesbSummary_ucesb_2eproto.base);
  return *internal_default_instance();
}


void UcesbSummary::Clear() {
// @@protoc_insertion_point(message_clear_start:frs_monitor.UcesbSummary)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  triggers_.Clear();
  server_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  analserver_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&event_no_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&spill_ctr_) -
      reinterpret_cast<char*>(&event_no_)) + sizeof(spill_ctr_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UcesbSummary::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string server = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_server();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "frs_monitor.UcesbSummary.server"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 clients = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          clients_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 event_no = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          event_no_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 wr = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          wr_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .frs_monitor.UcesbSummary.Triggers triggers = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_triggers(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // bool onspill = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          onspill_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 lastspill = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          lastspill_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 spilltime = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          spilltime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 extrtime = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          extrtime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 spill_ctr = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          spill_ctr_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string analserver = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          auto str = _internal_mutable_analserver();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "frs_monitor.UcesbSummary.analserver"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UcesbSummary::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:frs_monitor.UcesbSummary)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string server = 1;
  if (this->server().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_server().data(), static_cast<int>(this->_internal_server().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "frs_monitor.UcesbSummary.server");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_server(), target);
  }

  // int32 clients = 2;
  if (this->clients() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_clients(), target);
  }

  // uint64 event_no = 3;
  if (this->event_no() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->_internal_event_no(), target);
  }

  // int32 time = 4;
  if (this->time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_time(), target);
  }

  // uint64 wr = 5;
  if (this->wr() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->_internal_wr(), target);
  }

  // repeated .frs_monitor.UcesbSummary.Triggers triggers = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_triggers_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_triggers(i), target, stream);
  }

  // bool onspill = 7;
  if (this->onspill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(7, this->_internal_onspill(), target);
  }

  // int32 lastspill = 8;
  if (this->lastspill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(8, this->_internal_lastspill(), target);
  }

  // int32 spilltime = 9;
  if (this->spilltime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(9, this->_internal_spilltime(), target);
  }

  // int32 extrtime = 10;
  if (this->extrtime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(10, this->_internal_extrtime(), target);
  }

  // uint32 spill_ctr = 11;
  if (this->spill_ctr() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(11, this->_internal_spill_ctr(), target);
  }

  // string analserver = 12;
  if (this->analserver().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_analserver().data(), static_cast<int>(this->_internal_analserver().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "frs_monitor.UcesbSummary.analserver");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_analserver(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:frs_monitor.UcesbSummary)
  return target;
}

size_t UcesbSummary::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:frs_monitor.UcesbSummary)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .frs_monitor.UcesbSummary.Triggers triggers = 6;
  total_size += 1UL * this->_internal_triggers_size();
  for (const auto& msg : this->triggers_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string server = 1;
  if (this->server().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_server());
  }

  // string analserver = 12;
  if (this->analserver().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_analserver());
  }

  // uint64 event_no = 3;
  if (this->event_no() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_event_no());
  }

  // int32 clients = 2;
  if (this->clients() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_clients());
  }

  // int32 time = 4;
  if (this->time() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_time());
  }

  // uint64 wr = 5;
  if (this->wr() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_wr());
  }

  // bool onspill = 7;
  if (this->onspill() != 0) {
    total_size += 1 + 1;
  }

  // int32 lastspill = 8;
  if (this->lastspill() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_lastspill());
  }

  // int32 spilltime = 9;
  if (this->spilltime() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_spilltime());
  }

  // int32 extrtime = 10;
  if (this->extrtime() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_extrtime());
  }

  // uint32 spill_ctr = 11;
  if (this->spill_ctr() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_spill_ctr());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UcesbSummary::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:frs_monitor.UcesbSummary)
  GOOGLE_DCHECK_NE(&from, this);
  const UcesbSummary* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UcesbSummary>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:frs_monitor.UcesbSummary)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:frs_monitor.UcesbSummary)
    MergeFrom(*source);
  }
}

void UcesbSummary::MergeFrom(const UcesbSummary& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:frs_monitor.UcesbSummary)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  triggers_.MergeFrom(from.triggers_);
  if (from.server().size() > 0) {
    _internal_set_server(from._internal_server());
  }
  if (from.analserver().size() > 0) {
    _internal_set_analserver(from._internal_analserver());
  }
  if (from.event_no() != 0) {
    _internal_set_event_no(from._internal_event_no());
  }
  if (from.clients() != 0) {
    _internal_set_clients(from._internal_clients());
  }
  if (from.time() != 0) {
    _internal_set_time(from._internal_time());
  }
  if (from.wr() != 0) {
    _internal_set_wr(from._internal_wr());
  }
  if (from.onspill() != 0) {
    _internal_set_onspill(from._internal_onspill());
  }
  if (from.lastspill() != 0) {
    _internal_set_lastspill(from._internal_lastspill());
  }
  if (from.spilltime() != 0) {
    _internal_set_spilltime(from._internal_spilltime());
  }
  if (from.extrtime() != 0) {
    _internal_set_extrtime(from._internal_extrtime());
  }
  if (from.spill_ctr() != 0) {
    _internal_set_spill_ctr(from._internal_spill_ctr());
  }
}

void UcesbSummary::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:frs_monitor.UcesbSummary)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UcesbSummary::CopyFrom(const UcesbSummary& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:frs_monitor.UcesbSummary)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UcesbSummary::IsInitialized() const {
  return true;
}

void UcesbSummary::InternalSwap(UcesbSummary* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  triggers_.InternalSwap(&other->triggers_);
  server_.Swap(&other->server_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  analserver_.Swap(&other->analserver_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UcesbSummary, spill_ctr_)
      + sizeof(UcesbSummary::spill_ctr_)
      - PROTOBUF_FIELD_OFFSET(UcesbSummary, event_no_)>(
          reinterpret_cast<char*>(&event_no_),
          reinterpret_cast<char*>(&other->event_no_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UcesbSummary::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void LogEntry::InitAsDefaultInstance() {
}
class LogEntry::_Internal {
 public:
};

LogEntry::LogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:frs_monitor.LogEntry)
}
LogEntry::LogEntry(const LogEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_message().empty()) {
    message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_message(),
      GetArena());
  }
  severity_ = from.severity_;
  // @@protoc_insertion_point(copy_constructor:frs_monitor.LogEntry)
}

void LogEntry::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LogEntry_ucesb_2eproto.base);
  message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  severity_ = 0;
}

LogEntry::~LogEntry() {
  // @@protoc_insertion_point(destructor:frs_monitor.LogEntry)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LogEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  message_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void LogEntry::ArenaDtor(void* object) {
  LogEntry* _this = reinterpret_cast< LogEntry* >(object);
  (void)_this;
}
void LogEntry::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LogEntry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LogEntry& LogEntry::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LogEntry_ucesb_2eproto.base);
  return *internal_default_instance();
}


void LogEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:frs_monitor.LogEntry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  severity_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogEntry::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .frs_monitor.LogEntry.LogSeverity severity = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_severity(static_cast<::frs_monitor::LogEntry_LogSeverity>(val));
        } else goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "frs_monitor.LogEntry.message"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LogEntry::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:frs_monitor.LogEntry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .frs_monitor.LogEntry.LogSeverity severity = 1;
  if (this->severity() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_severity(), target);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "frs_monitor.LogEntry.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:frs_monitor.LogEntry)
  return target;
}

size_t LogEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:frs_monitor.LogEntry)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .frs_monitor.LogEntry.LogSeverity severity = 1;
  if (this->severity() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_severity());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LogEntry::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:frs_monitor.LogEntry)
  GOOGLE_DCHECK_NE(&from, this);
  const LogEntry* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LogEntry>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:frs_monitor.LogEntry)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:frs_monitor.LogEntry)
    MergeFrom(*source);
  }
}

void LogEntry::MergeFrom(const LogEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:frs_monitor.LogEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {
    _internal_set_message(from._internal_message());
  }
  if (from.severity() != 0) {
    _internal_set_severity(from._internal_severity());
  }
}

void LogEntry::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:frs_monitor.LogEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LogEntry::CopyFrom(const LogEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:frs_monitor.LogEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogEntry::IsInitialized() const {
  return true;
}

void LogEntry::InternalSwap(LogEntry* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  message_.Swap(&other->message_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(severity_, other->severity_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LogEntry::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void UcesbReport::InitAsDefaultInstance() {
  ::frs_monitor::_UcesbReport_default_instance_._instance.get_mutable()->summary_ = const_cast< ::frs_monitor::UcesbSummary*>(
      ::frs_monitor::UcesbSummary::internal_default_instance());
}
class UcesbReport::_Internal {
 public:
  static const ::frs_monitor::UcesbSummary& summary(const UcesbReport* msg);
};

const ::frs_monitor::UcesbSummary&
UcesbReport::_Internal::summary(const UcesbReport* msg) {
  return *msg->summary_;
}
UcesbReport::UcesbReport(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  logs_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:frs_monitor.UcesbReport)
}
UcesbReport::UcesbReport(const UcesbReport& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      logs_(from.logs_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_summary()) {
    summary_ = new ::frs_monitor::UcesbSummary(*from.summary_);
  } else {
    summary_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:frs_monitor.UcesbReport)
}

void UcesbReport::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UcesbReport_ucesb_2eproto.base);
  summary_ = nullptr;
}

UcesbReport::~UcesbReport() {
  // @@protoc_insertion_point(destructor:frs_monitor.UcesbReport)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UcesbReport::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete summary_;
}

void UcesbReport::ArenaDtor(void* object) {
  UcesbReport* _this = reinterpret_cast< UcesbReport* >(object);
  (void)_this;
}
void UcesbReport::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UcesbReport::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UcesbReport& UcesbReport::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UcesbReport_ucesb_2eproto.base);
  return *internal_default_instance();
}


void UcesbReport::Clear() {
// @@protoc_insertion_point(message_clear_start:frs_monitor.UcesbReport)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  logs_.Clear();
  if (GetArena() == nullptr && summary_ != nullptr) {
    delete summary_;
  }
  summary_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UcesbReport::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .frs_monitor.UcesbSummary summary = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_summary(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .frs_monitor.LogEntry logs = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_logs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UcesbReport::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:frs_monitor.UcesbReport)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .frs_monitor.UcesbSummary summary = 1;
  if (this->has_summary()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::summary(this), target, stream);
  }

  // repeated .frs_monitor.LogEntry logs = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_logs_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_logs(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:frs_monitor.UcesbReport)
  return target;
}

size_t UcesbReport::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:frs_monitor.UcesbReport)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .frs_monitor.LogEntry logs = 4;
  total_size += 1UL * this->_internal_logs_size();
  for (const auto& msg : this->logs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .frs_monitor.UcesbSummary summary = 1;
  if (this->has_summary()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *summary_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UcesbReport::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:frs_monitor.UcesbReport)
  GOOGLE_DCHECK_NE(&from, this);
  const UcesbReport* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UcesbReport>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:frs_monitor.UcesbReport)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:frs_monitor.UcesbReport)
    MergeFrom(*source);
  }
}

void UcesbReport::MergeFrom(const UcesbReport& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:frs_monitor.UcesbReport)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  logs_.MergeFrom(from.logs_);
  if (from.has_summary()) {
    _internal_mutable_summary()->::frs_monitor::UcesbSummary::MergeFrom(from._internal_summary());
  }
}

void UcesbReport::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:frs_monitor.UcesbReport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UcesbReport::CopyFrom(const UcesbReport& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:frs_monitor.UcesbReport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UcesbReport::IsInitialized() const {
  return true;
}

void UcesbReport::InternalSwap(UcesbReport* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  logs_.InternalSwap(&other->logs_);
  swap(summary_, other->summary_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UcesbReport::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace frs_monitor
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::frs_monitor::UcesbSummary_Triggers* Arena::CreateMaybeMessage< ::frs_monitor::UcesbSummary_Triggers >(Arena* arena) {
  return Arena::CreateMessageInternal< ::frs_monitor::UcesbSummary_Triggers >(arena);
}
template<> PROTOBUF_NOINLINE ::frs_monitor::UcesbSummary* Arena::CreateMaybeMessage< ::frs_monitor::UcesbSummary >(Arena* arena) {
  return Arena::CreateMessageInternal< ::frs_monitor::UcesbSummary >(arena);
}
template<> PROTOBUF_NOINLINE ::frs_monitor::LogEntry* Arena::CreateMaybeMessage< ::frs_monitor::LogEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::frs_monitor::LogEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::frs_monitor::UcesbReport* Arena::CreateMaybeMessage< ::frs_monitor::UcesbReport >(Arena* arena) {
  return Arena::CreateMessageInternal< ::frs_monitor::UcesbReport >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
