// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ucesb.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ucesb_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ucesb_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ucesb_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ucesb_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ucesb_2eproto;
namespace frs_monitor {
class LogEntry;
class LogEntryDefaultTypeInternal;
extern LogEntryDefaultTypeInternal _LogEntry_default_instance_;
class UcesbReport;
class UcesbReportDefaultTypeInternal;
extern UcesbReportDefaultTypeInternal _UcesbReport_default_instance_;
class UcesbSummary;
class UcesbSummaryDefaultTypeInternal;
extern UcesbSummaryDefaultTypeInternal _UcesbSummary_default_instance_;
class UcesbSummary_Triggers;
class UcesbSummary_TriggersDefaultTypeInternal;
extern UcesbSummary_TriggersDefaultTypeInternal _UcesbSummary_Triggers_default_instance_;
}  // namespace frs_monitor
PROTOBUF_NAMESPACE_OPEN
template<> ::frs_monitor::LogEntry* Arena::CreateMaybeMessage<::frs_monitor::LogEntry>(Arena*);
template<> ::frs_monitor::UcesbReport* Arena::CreateMaybeMessage<::frs_monitor::UcesbReport>(Arena*);
template<> ::frs_monitor::UcesbSummary* Arena::CreateMaybeMessage<::frs_monitor::UcesbSummary>(Arena*);
template<> ::frs_monitor::UcesbSummary_Triggers* Arena::CreateMaybeMessage<::frs_monitor::UcesbSummary_Triggers>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace frs_monitor {

enum LogEntry_LogSeverity : int {
  LogEntry_LogSeverity_NORMAL = 0,
  LogEntry_LogSeverity_WARNING = 1,
  LogEntry_LogSeverity_ERROR = 2,
  LogEntry_LogSeverity_LogEntry_LogSeverity_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  LogEntry_LogSeverity_LogEntry_LogSeverity_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool LogEntry_LogSeverity_IsValid(int value);
constexpr LogEntry_LogSeverity LogEntry_LogSeverity_LogSeverity_MIN = LogEntry_LogSeverity_NORMAL;
constexpr LogEntry_LogSeverity LogEntry_LogSeverity_LogSeverity_MAX = LogEntry_LogSeverity_ERROR;
constexpr int LogEntry_LogSeverity_LogSeverity_ARRAYSIZE = LogEntry_LogSeverity_LogSeverity_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogEntry_LogSeverity_descriptor();
template<typename T>
inline const std::string& LogEntry_LogSeverity_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LogEntry_LogSeverity>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LogEntry_LogSeverity_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LogEntry_LogSeverity_descriptor(), enum_t_value);
}
inline bool LogEntry_LogSeverity_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogEntry_LogSeverity* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogEntry_LogSeverity>(
    LogEntry_LogSeverity_descriptor(), name, value);
}
// ===================================================================

class UcesbSummary_Triggers PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frs_monitor.UcesbSummary.Triggers) */ {
 public:
  inline UcesbSummary_Triggers() : UcesbSummary_Triggers(nullptr) {}
  virtual ~UcesbSummary_Triggers();

  UcesbSummary_Triggers(const UcesbSummary_Triggers& from);
  UcesbSummary_Triggers(UcesbSummary_Triggers&& from) noexcept
    : UcesbSummary_Triggers() {
    *this = ::std::move(from);
  }

  inline UcesbSummary_Triggers& operator=(const UcesbSummary_Triggers& from) {
    CopyFrom(from);
    return *this;
  }
  inline UcesbSummary_Triggers& operator=(UcesbSummary_Triggers&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UcesbSummary_Triggers& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UcesbSummary_Triggers* internal_default_instance() {
    return reinterpret_cast<const UcesbSummary_Triggers*>(
               &_UcesbSummary_Triggers_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UcesbSummary_Triggers& a, UcesbSummary_Triggers& b) {
    a.Swap(&b);
  }
  inline void Swap(UcesbSummary_Triggers* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UcesbSummary_Triggers* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UcesbSummary_Triggers* New() const final {
    return CreateMaybeMessage<UcesbSummary_Triggers>(nullptr);
  }

  UcesbSummary_Triggers* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UcesbSummary_Triggers>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UcesbSummary_Triggers& from);
  void MergeFrom(const UcesbSummary_Triggers& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UcesbSummary_Triggers* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frs_monitor.UcesbSummary.Triggers";
  }
  protected:
  explicit UcesbSummary_Triggers(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ucesb_2eproto);
    return ::descriptor_table_ucesb_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kRateFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 rate = 2;
  void clear_rate();
  ::PROTOBUF_NAMESPACE_ID::int32 rate() const;
  void set_rate(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_rate() const;
  void _internal_set_rate(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:frs_monitor.UcesbSummary.Triggers)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::int32 rate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ucesb_2eproto;
};
// -------------------------------------------------------------------

class UcesbSummary PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frs_monitor.UcesbSummary) */ {
 public:
  inline UcesbSummary() : UcesbSummary(nullptr) {}
  virtual ~UcesbSummary();

  UcesbSummary(const UcesbSummary& from);
  UcesbSummary(UcesbSummary&& from) noexcept
    : UcesbSummary() {
    *this = ::std::move(from);
  }

  inline UcesbSummary& operator=(const UcesbSummary& from) {
    CopyFrom(from);
    return *this;
  }
  inline UcesbSummary& operator=(UcesbSummary&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UcesbSummary& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UcesbSummary* internal_default_instance() {
    return reinterpret_cast<const UcesbSummary*>(
               &_UcesbSummary_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UcesbSummary& a, UcesbSummary& b) {
    a.Swap(&b);
  }
  inline void Swap(UcesbSummary* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UcesbSummary* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UcesbSummary* New() const final {
    return CreateMaybeMessage<UcesbSummary>(nullptr);
  }

  UcesbSummary* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UcesbSummary>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UcesbSummary& from);
  void MergeFrom(const UcesbSummary& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UcesbSummary* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frs_monitor.UcesbSummary";
  }
  protected:
  explicit UcesbSummary(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ucesb_2eproto);
    return ::descriptor_table_ucesb_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef UcesbSummary_Triggers Triggers;

  // accessors -------------------------------------------------------

  enum : int {
    kTriggersFieldNumber = 6,
    kServerFieldNumber = 1,
    kAnalserverFieldNumber = 12,
    kEventNoFieldNumber = 3,
    kClientsFieldNumber = 2,
    kTimeFieldNumber = 4,
    kWrFieldNumber = 5,
    kOnspillFieldNumber = 7,
    kLastspillFieldNumber = 8,
    kSpilltimeFieldNumber = 9,
    kExtrtimeFieldNumber = 10,
    kSpillCtrFieldNumber = 11,
  };
  // repeated .frs_monitor.UcesbSummary.Triggers triggers = 6;
  int triggers_size() const;
  private:
  int _internal_triggers_size() const;
  public:
  void clear_triggers();
  ::frs_monitor::UcesbSummary_Triggers* mutable_triggers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::UcesbSummary_Triggers >*
      mutable_triggers();
  private:
  const ::frs_monitor::UcesbSummary_Triggers& _internal_triggers(int index) const;
  ::frs_monitor::UcesbSummary_Triggers* _internal_add_triggers();
  public:
  const ::frs_monitor::UcesbSummary_Triggers& triggers(int index) const;
  ::frs_monitor::UcesbSummary_Triggers* add_triggers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::UcesbSummary_Triggers >&
      triggers() const;

  // string server = 1;
  void clear_server();
  const std::string& server() const;
  void set_server(const std::string& value);
  void set_server(std::string&& value);
  void set_server(const char* value);
  void set_server(const char* value, size_t size);
  std::string* mutable_server();
  std::string* release_server();
  void set_allocated_server(std::string* server);
  private:
  const std::string& _internal_server() const;
  void _internal_set_server(const std::string& value);
  std::string* _internal_mutable_server();
  public:

  // string analserver = 12;
  void clear_analserver();
  const std::string& analserver() const;
  void set_analserver(const std::string& value);
  void set_analserver(std::string&& value);
  void set_analserver(const char* value);
  void set_analserver(const char* value, size_t size);
  std::string* mutable_analserver();
  std::string* release_analserver();
  void set_allocated_analserver(std::string* analserver);
  private:
  const std::string& _internal_analserver() const;
  void _internal_set_analserver(const std::string& value);
  std::string* _internal_mutable_analserver();
  public:

  // uint64 event_no = 3;
  void clear_event_no();
  ::PROTOBUF_NAMESPACE_ID::uint64 event_no() const;
  void set_event_no(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_event_no() const;
  void _internal_set_event_no(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int32 clients = 2;
  void clear_clients();
  ::PROTOBUF_NAMESPACE_ID::int32 clients() const;
  void set_clients(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clients() const;
  void _internal_set_clients(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 time = 4;
  void clear_time();
  ::PROTOBUF_NAMESPACE_ID::int32 time() const;
  void set_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_time() const;
  void _internal_set_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // uint64 wr = 5;
  void clear_wr();
  ::PROTOBUF_NAMESPACE_ID::uint64 wr() const;
  void set_wr(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_wr() const;
  void _internal_set_wr(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool onspill = 7;
  void clear_onspill();
  bool onspill() const;
  void set_onspill(bool value);
  private:
  bool _internal_onspill() const;
  void _internal_set_onspill(bool value);
  public:

  // int32 lastspill = 8;
  void clear_lastspill();
  ::PROTOBUF_NAMESPACE_ID::int32 lastspill() const;
  void set_lastspill(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lastspill() const;
  void _internal_set_lastspill(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 spilltime = 9;
  void clear_spilltime();
  ::PROTOBUF_NAMESPACE_ID::int32 spilltime() const;
  void set_spilltime(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_spilltime() const;
  void _internal_set_spilltime(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 extrtime = 10;
  void clear_extrtime();
  ::PROTOBUF_NAMESPACE_ID::int32 extrtime() const;
  void set_extrtime(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_extrtime() const;
  void _internal_set_extrtime(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // uint32 spill_ctr = 11;
  void clear_spill_ctr();
  ::PROTOBUF_NAMESPACE_ID::uint32 spill_ctr() const;
  void set_spill_ctr(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_spill_ctr() const;
  void _internal_set_spill_ctr(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:frs_monitor.UcesbSummary)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::UcesbSummary_Triggers > triggers_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr analserver_;
  ::PROTOBUF_NAMESPACE_ID::uint64 event_no_;
  ::PROTOBUF_NAMESPACE_ID::int32 clients_;
  ::PROTOBUF_NAMESPACE_ID::int32 time_;
  ::PROTOBUF_NAMESPACE_ID::uint64 wr_;
  bool onspill_;
  ::PROTOBUF_NAMESPACE_ID::int32 lastspill_;
  ::PROTOBUF_NAMESPACE_ID::int32 spilltime_;
  ::PROTOBUF_NAMESPACE_ID::int32 extrtime_;
  ::PROTOBUF_NAMESPACE_ID::uint32 spill_ctr_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ucesb_2eproto;
};
// -------------------------------------------------------------------

class LogEntry PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frs_monitor.LogEntry) */ {
 public:
  inline LogEntry() : LogEntry(nullptr) {}
  virtual ~LogEntry();

  LogEntry(const LogEntry& from);
  LogEntry(LogEntry&& from) noexcept
    : LogEntry() {
    *this = ::std::move(from);
  }

  inline LogEntry& operator=(const LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogEntry& operator=(LogEntry&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogEntry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogEntry* internal_default_instance() {
    return reinterpret_cast<const LogEntry*>(
               &_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LogEntry& a, LogEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(LogEntry* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogEntry* New() const final {
    return CreateMaybeMessage<LogEntry>(nullptr);
  }

  LogEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogEntry>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogEntry& from);
  void MergeFrom(const LogEntry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogEntry* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frs_monitor.LogEntry";
  }
  protected:
  explicit LogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ucesb_2eproto);
    return ::descriptor_table_ucesb_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef LogEntry_LogSeverity LogSeverity;
  static constexpr LogSeverity NORMAL =
    LogEntry_LogSeverity_NORMAL;
  static constexpr LogSeverity WARNING =
    LogEntry_LogSeverity_WARNING;
  static constexpr LogSeverity ERROR =
    LogEntry_LogSeverity_ERROR;
  static inline bool LogSeverity_IsValid(int value) {
    return LogEntry_LogSeverity_IsValid(value);
  }
  static constexpr LogSeverity LogSeverity_MIN =
    LogEntry_LogSeverity_LogSeverity_MIN;
  static constexpr LogSeverity LogSeverity_MAX =
    LogEntry_LogSeverity_LogSeverity_MAX;
  static constexpr int LogSeverity_ARRAYSIZE =
    LogEntry_LogSeverity_LogSeverity_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  LogSeverity_descriptor() {
    return LogEntry_LogSeverity_descriptor();
  }
  template<typename T>
  static inline const std::string& LogSeverity_Name(T enum_t_value) {
    static_assert(::std::is_same<T, LogSeverity>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function LogSeverity_Name.");
    return LogEntry_LogSeverity_Name(enum_t_value);
  }
  static inline bool LogSeverity_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      LogSeverity* value) {
    return LogEntry_LogSeverity_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kSeverityFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .frs_monitor.LogEntry.LogSeverity severity = 1;
  void clear_severity();
  ::frs_monitor::LogEntry_LogSeverity severity() const;
  void set_severity(::frs_monitor::LogEntry_LogSeverity value);
  private:
  ::frs_monitor::LogEntry_LogSeverity _internal_severity() const;
  void _internal_set_severity(::frs_monitor::LogEntry_LogSeverity value);
  public:

  // @@protoc_insertion_point(class_scope:frs_monitor.LogEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  int severity_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ucesb_2eproto;
};
// -------------------------------------------------------------------

class UcesbReport PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:frs_monitor.UcesbReport) */ {
 public:
  inline UcesbReport() : UcesbReport(nullptr) {}
  virtual ~UcesbReport();

  UcesbReport(const UcesbReport& from);
  UcesbReport(UcesbReport&& from) noexcept
    : UcesbReport() {
    *this = ::std::move(from);
  }

  inline UcesbReport& operator=(const UcesbReport& from) {
    CopyFrom(from);
    return *this;
  }
  inline UcesbReport& operator=(UcesbReport&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UcesbReport& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UcesbReport* internal_default_instance() {
    return reinterpret_cast<const UcesbReport*>(
               &_UcesbReport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(UcesbReport& a, UcesbReport& b) {
    a.Swap(&b);
  }
  inline void Swap(UcesbReport* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UcesbReport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UcesbReport* New() const final {
    return CreateMaybeMessage<UcesbReport>(nullptr);
  }

  UcesbReport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UcesbReport>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UcesbReport& from);
  void MergeFrom(const UcesbReport& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UcesbReport* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "frs_monitor.UcesbReport";
  }
  protected:
  explicit UcesbReport(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ucesb_2eproto);
    return ::descriptor_table_ucesb_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogsFieldNumber = 4,
    kSummaryFieldNumber = 1,
  };
  // repeated .frs_monitor.LogEntry logs = 4;
  int logs_size() const;
  private:
  int _internal_logs_size() const;
  public:
  void clear_logs();
  ::frs_monitor::LogEntry* mutable_logs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::LogEntry >*
      mutable_logs();
  private:
  const ::frs_monitor::LogEntry& _internal_logs(int index) const;
  ::frs_monitor::LogEntry* _internal_add_logs();
  public:
  const ::frs_monitor::LogEntry& logs(int index) const;
  ::frs_monitor::LogEntry* add_logs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::LogEntry >&
      logs() const;

  // .frs_monitor.UcesbSummary summary = 1;
  bool has_summary() const;
  private:
  bool _internal_has_summary() const;
  public:
  void clear_summary();
  const ::frs_monitor::UcesbSummary& summary() const;
  ::frs_monitor::UcesbSummary* release_summary();
  ::frs_monitor::UcesbSummary* mutable_summary();
  void set_allocated_summary(::frs_monitor::UcesbSummary* summary);
  private:
  const ::frs_monitor::UcesbSummary& _internal_summary() const;
  ::frs_monitor::UcesbSummary* _internal_mutable_summary();
  public:
  void unsafe_arena_set_allocated_summary(
      ::frs_monitor::UcesbSummary* summary);
  ::frs_monitor::UcesbSummary* unsafe_arena_release_summary();

  // @@protoc_insertion_point(class_scope:frs_monitor.UcesbReport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::LogEntry > logs_;
  ::frs_monitor::UcesbSummary* summary_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ucesb_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UcesbSummary_Triggers

// string name = 1;
inline void UcesbSummary_Triggers::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& UcesbSummary_Triggers::name() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.Triggers.name)
  return _internal_name();
}
inline void UcesbSummary_Triggers::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.Triggers.name)
}
inline std::string* UcesbSummary_Triggers::mutable_name() {
  // @@protoc_insertion_point(field_mutable:frs_monitor.UcesbSummary.Triggers.name)
  return _internal_mutable_name();
}
inline const std::string& UcesbSummary_Triggers::_internal_name() const {
  return name_.Get();
}
inline void UcesbSummary_Triggers::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UcesbSummary_Triggers::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:frs_monitor.UcesbSummary.Triggers.name)
}
inline void UcesbSummary_Triggers::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:frs_monitor.UcesbSummary.Triggers.name)
}
inline void UcesbSummary_Triggers::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:frs_monitor.UcesbSummary.Triggers.name)
}
inline std::string* UcesbSummary_Triggers::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UcesbSummary_Triggers::release_name() {
  // @@protoc_insertion_point(field_release:frs_monitor.UcesbSummary.Triggers.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UcesbSummary_Triggers::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:frs_monitor.UcesbSummary.Triggers.name)
}

// int32 rate = 2;
inline void UcesbSummary_Triggers::clear_rate() {
  rate_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary_Triggers::_internal_rate() const {
  return rate_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary_Triggers::rate() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.Triggers.rate)
  return _internal_rate();
}
inline void UcesbSummary_Triggers::_internal_set_rate(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  rate_ = value;
}
inline void UcesbSummary_Triggers::set_rate(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_rate(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.Triggers.rate)
}

// -------------------------------------------------------------------

// UcesbSummary

// string server = 1;
inline void UcesbSummary::clear_server() {
  server_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& UcesbSummary::server() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.server)
  return _internal_server();
}
inline void UcesbSummary::set_server(const std::string& value) {
  _internal_set_server(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.server)
}
inline std::string* UcesbSummary::mutable_server() {
  // @@protoc_insertion_point(field_mutable:frs_monitor.UcesbSummary.server)
  return _internal_mutable_server();
}
inline const std::string& UcesbSummary::_internal_server() const {
  return server_.Get();
}
inline void UcesbSummary::_internal_set_server(const std::string& value) {
  
  server_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UcesbSummary::set_server(std::string&& value) {
  
  server_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:frs_monitor.UcesbSummary.server)
}
inline void UcesbSummary::set_server(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  server_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:frs_monitor.UcesbSummary.server)
}
inline void UcesbSummary::set_server(const char* value,
    size_t size) {
  
  server_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:frs_monitor.UcesbSummary.server)
}
inline std::string* UcesbSummary::_internal_mutable_server() {
  
  return server_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UcesbSummary::release_server() {
  // @@protoc_insertion_point(field_release:frs_monitor.UcesbSummary.server)
  return server_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UcesbSummary::set_allocated_server(std::string* server) {
  if (server != nullptr) {
    
  } else {
    
  }
  server_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), server,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:frs_monitor.UcesbSummary.server)
}

// int32 clients = 2;
inline void UcesbSummary::clear_clients() {
  clients_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::_internal_clients() const {
  return clients_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::clients() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.clients)
  return _internal_clients();
}
inline void UcesbSummary::_internal_set_clients(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clients_ = value;
}
inline void UcesbSummary::set_clients(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clients(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.clients)
}

// uint64 event_no = 3;
inline void UcesbSummary::clear_event_no() {
  event_no_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UcesbSummary::_internal_event_no() const {
  return event_no_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UcesbSummary::event_no() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.event_no)
  return _internal_event_no();
}
inline void UcesbSummary::_internal_set_event_no(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  event_no_ = value;
}
inline void UcesbSummary::set_event_no(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_event_no(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.event_no)
}

// int32 time = 4;
inline void UcesbSummary::clear_time() {
  time_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::_internal_time() const {
  return time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::time() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.time)
  return _internal_time();
}
inline void UcesbSummary::_internal_set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  time_ = value;
}
inline void UcesbSummary::set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.time)
}

// uint64 wr = 5;
inline void UcesbSummary::clear_wr() {
  wr_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UcesbSummary::_internal_wr() const {
  return wr_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UcesbSummary::wr() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.wr)
  return _internal_wr();
}
inline void UcesbSummary::_internal_set_wr(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  wr_ = value;
}
inline void UcesbSummary::set_wr(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_wr(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.wr)
}

// repeated .frs_monitor.UcesbSummary.Triggers triggers = 6;
inline int UcesbSummary::_internal_triggers_size() const {
  return triggers_.size();
}
inline int UcesbSummary::triggers_size() const {
  return _internal_triggers_size();
}
inline void UcesbSummary::clear_triggers() {
  triggers_.Clear();
}
inline ::frs_monitor::UcesbSummary_Triggers* UcesbSummary::mutable_triggers(int index) {
  // @@protoc_insertion_point(field_mutable:frs_monitor.UcesbSummary.triggers)
  return triggers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::UcesbSummary_Triggers >*
UcesbSummary::mutable_triggers() {
  // @@protoc_insertion_point(field_mutable_list:frs_monitor.UcesbSummary.triggers)
  return &triggers_;
}
inline const ::frs_monitor::UcesbSummary_Triggers& UcesbSummary::_internal_triggers(int index) const {
  return triggers_.Get(index);
}
inline const ::frs_monitor::UcesbSummary_Triggers& UcesbSummary::triggers(int index) const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.triggers)
  return _internal_triggers(index);
}
inline ::frs_monitor::UcesbSummary_Triggers* UcesbSummary::_internal_add_triggers() {
  return triggers_.Add();
}
inline ::frs_monitor::UcesbSummary_Triggers* UcesbSummary::add_triggers() {
  // @@protoc_insertion_point(field_add:frs_monitor.UcesbSummary.triggers)
  return _internal_add_triggers();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::UcesbSummary_Triggers >&
UcesbSummary::triggers() const {
  // @@protoc_insertion_point(field_list:frs_monitor.UcesbSummary.triggers)
  return triggers_;
}

// bool onspill = 7;
inline void UcesbSummary::clear_onspill() {
  onspill_ = false;
}
inline bool UcesbSummary::_internal_onspill() const {
  return onspill_;
}
inline bool UcesbSummary::onspill() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.onspill)
  return _internal_onspill();
}
inline void UcesbSummary::_internal_set_onspill(bool value) {
  
  onspill_ = value;
}
inline void UcesbSummary::set_onspill(bool value) {
  _internal_set_onspill(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.onspill)
}

// int32 lastspill = 8;
inline void UcesbSummary::clear_lastspill() {
  lastspill_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::_internal_lastspill() const {
  return lastspill_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::lastspill() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.lastspill)
  return _internal_lastspill();
}
inline void UcesbSummary::_internal_set_lastspill(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  lastspill_ = value;
}
inline void UcesbSummary::set_lastspill(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_lastspill(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.lastspill)
}

// int32 spilltime = 9;
inline void UcesbSummary::clear_spilltime() {
  spilltime_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::_internal_spilltime() const {
  return spilltime_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::spilltime() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.spilltime)
  return _internal_spilltime();
}
inline void UcesbSummary::_internal_set_spilltime(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  spilltime_ = value;
}
inline void UcesbSummary::set_spilltime(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_spilltime(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.spilltime)
}

// int32 extrtime = 10;
inline void UcesbSummary::clear_extrtime() {
  extrtime_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::_internal_extrtime() const {
  return extrtime_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UcesbSummary::extrtime() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.extrtime)
  return _internal_extrtime();
}
inline void UcesbSummary::_internal_set_extrtime(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  extrtime_ = value;
}
inline void UcesbSummary::set_extrtime(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_extrtime(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.extrtime)
}

// uint32 spill_ctr = 11;
inline void UcesbSummary::clear_spill_ctr() {
  spill_ctr_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UcesbSummary::_internal_spill_ctr() const {
  return spill_ctr_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UcesbSummary::spill_ctr() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.spill_ctr)
  return _internal_spill_ctr();
}
inline void UcesbSummary::_internal_set_spill_ctr(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  spill_ctr_ = value;
}
inline void UcesbSummary::set_spill_ctr(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_spill_ctr(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.spill_ctr)
}

// string analserver = 12;
inline void UcesbSummary::clear_analserver() {
  analserver_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& UcesbSummary::analserver() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbSummary.analserver)
  return _internal_analserver();
}
inline void UcesbSummary::set_analserver(const std::string& value) {
  _internal_set_analserver(value);
  // @@protoc_insertion_point(field_set:frs_monitor.UcesbSummary.analserver)
}
inline std::string* UcesbSummary::mutable_analserver() {
  // @@protoc_insertion_point(field_mutable:frs_monitor.UcesbSummary.analserver)
  return _internal_mutable_analserver();
}
inline const std::string& UcesbSummary::_internal_analserver() const {
  return analserver_.Get();
}
inline void UcesbSummary::_internal_set_analserver(const std::string& value) {
  
  analserver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UcesbSummary::set_analserver(std::string&& value) {
  
  analserver_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:frs_monitor.UcesbSummary.analserver)
}
inline void UcesbSummary::set_analserver(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  analserver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:frs_monitor.UcesbSummary.analserver)
}
inline void UcesbSummary::set_analserver(const char* value,
    size_t size) {
  
  analserver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:frs_monitor.UcesbSummary.analserver)
}
inline std::string* UcesbSummary::_internal_mutable_analserver() {
  
  return analserver_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UcesbSummary::release_analserver() {
  // @@protoc_insertion_point(field_release:frs_monitor.UcesbSummary.analserver)
  return analserver_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UcesbSummary::set_allocated_analserver(std::string* analserver) {
  if (analserver != nullptr) {
    
  } else {
    
  }
  analserver_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), analserver,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:frs_monitor.UcesbSummary.analserver)
}

// -------------------------------------------------------------------

// LogEntry

// .frs_monitor.LogEntry.LogSeverity severity = 1;
inline void LogEntry::clear_severity() {
  severity_ = 0;
}
inline ::frs_monitor::LogEntry_LogSeverity LogEntry::_internal_severity() const {
  return static_cast< ::frs_monitor::LogEntry_LogSeverity >(severity_);
}
inline ::frs_monitor::LogEntry_LogSeverity LogEntry::severity() const {
  // @@protoc_insertion_point(field_get:frs_monitor.LogEntry.severity)
  return _internal_severity();
}
inline void LogEntry::_internal_set_severity(::frs_monitor::LogEntry_LogSeverity value) {
  
  severity_ = value;
}
inline void LogEntry::set_severity(::frs_monitor::LogEntry_LogSeverity value) {
  _internal_set_severity(value);
  // @@protoc_insertion_point(field_set:frs_monitor.LogEntry.severity)
}

// string message = 2;
inline void LogEntry::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogEntry::message() const {
  // @@protoc_insertion_point(field_get:frs_monitor.LogEntry.message)
  return _internal_message();
}
inline void LogEntry::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:frs_monitor.LogEntry.message)
}
inline std::string* LogEntry::mutable_message() {
  // @@protoc_insertion_point(field_mutable:frs_monitor.LogEntry.message)
  return _internal_mutable_message();
}
inline const std::string& LogEntry::_internal_message() const {
  return message_.Get();
}
inline void LogEntry::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogEntry::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:frs_monitor.LogEntry.message)
}
inline void LogEntry::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:frs_monitor.LogEntry.message)
}
inline void LogEntry::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:frs_monitor.LogEntry.message)
}
inline std::string* LogEntry::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogEntry::release_message() {
  // @@protoc_insertion_point(field_release:frs_monitor.LogEntry.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogEntry::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:frs_monitor.LogEntry.message)
}

// -------------------------------------------------------------------

// UcesbReport

// .frs_monitor.UcesbSummary summary = 1;
inline bool UcesbReport::_internal_has_summary() const {
  return this != internal_default_instance() && summary_ != nullptr;
}
inline bool UcesbReport::has_summary() const {
  return _internal_has_summary();
}
inline void UcesbReport::clear_summary() {
  if (GetArena() == nullptr && summary_ != nullptr) {
    delete summary_;
  }
  summary_ = nullptr;
}
inline const ::frs_monitor::UcesbSummary& UcesbReport::_internal_summary() const {
  const ::frs_monitor::UcesbSummary* p = summary_;
  return p != nullptr ? *p : *reinterpret_cast<const ::frs_monitor::UcesbSummary*>(
      &::frs_monitor::_UcesbSummary_default_instance_);
}
inline const ::frs_monitor::UcesbSummary& UcesbReport::summary() const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbReport.summary)
  return _internal_summary();
}
inline void UcesbReport::unsafe_arena_set_allocated_summary(
    ::frs_monitor::UcesbSummary* summary) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(summary_);
  }
  summary_ = summary;
  if (summary) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:frs_monitor.UcesbReport.summary)
}
inline ::frs_monitor::UcesbSummary* UcesbReport::release_summary() {
  
  ::frs_monitor::UcesbSummary* temp = summary_;
  summary_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::frs_monitor::UcesbSummary* UcesbReport::unsafe_arena_release_summary() {
  // @@protoc_insertion_point(field_release:frs_monitor.UcesbReport.summary)
  
  ::frs_monitor::UcesbSummary* temp = summary_;
  summary_ = nullptr;
  return temp;
}
inline ::frs_monitor::UcesbSummary* UcesbReport::_internal_mutable_summary() {
  
  if (summary_ == nullptr) {
    auto* p = CreateMaybeMessage<::frs_monitor::UcesbSummary>(GetArena());
    summary_ = p;
  }
  return summary_;
}
inline ::frs_monitor::UcesbSummary* UcesbReport::mutable_summary() {
  // @@protoc_insertion_point(field_mutable:frs_monitor.UcesbReport.summary)
  return _internal_mutable_summary();
}
inline void UcesbReport::set_allocated_summary(::frs_monitor::UcesbSummary* summary) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete summary_;
  }
  if (summary) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(summary);
    if (message_arena != submessage_arena) {
      summary = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, summary, submessage_arena);
    }
    
  } else {
    
  }
  summary_ = summary;
  // @@protoc_insertion_point(field_set_allocated:frs_monitor.UcesbReport.summary)
}

// repeated .frs_monitor.LogEntry logs = 4;
inline int UcesbReport::_internal_logs_size() const {
  return logs_.size();
}
inline int UcesbReport::logs_size() const {
  return _internal_logs_size();
}
inline void UcesbReport::clear_logs() {
  logs_.Clear();
}
inline ::frs_monitor::LogEntry* UcesbReport::mutable_logs(int index) {
  // @@protoc_insertion_point(field_mutable:frs_monitor.UcesbReport.logs)
  return logs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::LogEntry >*
UcesbReport::mutable_logs() {
  // @@protoc_insertion_point(field_mutable_list:frs_monitor.UcesbReport.logs)
  return &logs_;
}
inline const ::frs_monitor::LogEntry& UcesbReport::_internal_logs(int index) const {
  return logs_.Get(index);
}
inline const ::frs_monitor::LogEntry& UcesbReport::logs(int index) const {
  // @@protoc_insertion_point(field_get:frs_monitor.UcesbReport.logs)
  return _internal_logs(index);
}
inline ::frs_monitor::LogEntry* UcesbReport::_internal_add_logs() {
  return logs_.Add();
}
inline ::frs_monitor::LogEntry* UcesbReport::add_logs() {
  // @@protoc_insertion_point(field_add:frs_monitor.UcesbReport.logs)
  return _internal_add_logs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::frs_monitor::LogEntry >&
UcesbReport::logs() const {
  // @@protoc_insertion_point(field_list:frs_monitor.UcesbReport.logs)
  return logs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace frs_monitor

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::frs_monitor::LogEntry_LogSeverity> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::frs_monitor::LogEntry_LogSeverity>() {
  return ::frs_monitor::LogEntry_LogSeverity_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ucesb_2eproto
